---
- name: create nginx dirs
  file:
    path: "{{ item|safe|trim }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode:   0755
    recurse: yes
  with_items:
    - "{{ nginx_opt_dir }}"
    - "{{ nginx_log_dir }}"
    - "{{ nginx_opt_dir }}/error-page"
    - "{{ nginx_opt_dir }}/site.d"
    - "{{ nginx_opt_dir }}/sites-enabled"
    - "{{ nginx_opt_dir }}/ssl"


- name: transfer nginx.conf configuration
  template:
    src: "{{ item }}"
    dest: "{{ nginx_opt_dir }}/nginx.conf"
  with_fileglob:
    - ../templates/config/nginx.conf

- name: transfer mime.types configuration
  template:
    src: "{{ item }}"
    dest: "{{ nginx_opt_dir }}/mime.types"
  with_fileglob:
    - ../templates/config/mime.types
