---

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: true

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: start nginx
  systemd:
    name: nginx
    state: started
